### PR TITLE
Update Django initial files for the setup

### PR DESCRIPTION
**Pull request by Nunthapop123**
Merge remote-tracking branch 'origin/main' just comes from pycharm but it does not change anything (maybe) if changes so decline this request :)

### CODE REVIEW

**Comment by gooddinosaur** [comment]
Good work Nunthapop.

**Review by gooddinosaur — COMMENTED** [review]
Good work Nunthapop.

**Comment by PeanutPK** [comment]
wdad

**Review by PeanutPK — APPROVED** [review]
yes

**Review by gooddinosaur — APPROVED** [review]
Approve

**Pull request merged**
